CREATE OR REPLACE TABLE h_reservas (
    id_reserva BIGINT NOT NULL,
    adultos INT,
    ninios INT,
    noches_finde INT,
    noches_semana INT,
    parking INT,
    id_tipo_habitacion BIGINT NOT NULL,
    antelacion_reserva INT,
    ind_habitual INT,
    cancelaciones_previas INT,
    estancias_previas INT,
    precio_medio DECIMAL(10,2),
    peticiones_especiales INT,
    ind_cancelada INT,
    fecha_llegada DATE,
    fecha_salida DATE,
    venta DECIMAL(10,2),
    id_cliente BIGINT NOT NULL,
    id_canal BIGINT NOT NULL,
    PRIMARY KEY (id_reserva),
    FOREIGN KEY (id_canal) REFERENCES D_CANAL_VENTA(id_canal),
    FOREIGN KEY (id_tipo_habitacion) REFERENCES D_TIPO_HABITACION(id_tipo_habitacion),
    FOREIGN KEY (id_cliente) REFERENCES D_CLIENTES(id_cliente)
);